### ISSUE TITLE
The TestFelixOnGateway tests are failing frequently

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calicoctl#1492]
I've spotted a number of failures with the TestFelixOnGateway test.  For example:

https://semaphoreci.com/calico/calicoctl/branches/master/builds/1188

It looks like the test might be a little flaky.  Note, though that I've only spotted the flakiness since fixing the STs to actually use the locally built version of calico/node.  Recently, when we moved to using quay.io as the default image, we had unknowingly "broken" the STs so that the calico/node would always be pulled from quay.

Upshot is twofold:
-  The STs would have been using the latest release of calico/node rather than the version built for the branch/master
-  The STs would have been slower because the image would end up being pulled every time we start calico/node.  This could potentially reduce some timing windows.

Not sure which of these might be the cause.  Or perhaps something else entirely.

**Comment by robbrockbank** [comment]
======================================================================
FAIL: test_egress_policy_can_block_through_traffic (tests.st.policy.test_felix_gateway.TestFelixOnGateway)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/tests/st/policy/test_felix_gateway.py", line 227, in test_egress_policy_can_block_through_traffic
    retry_until_success(self.assert_host_can_not_curl_ext, 3)
  File "/code/tests/st/utils/utils.py", line 118, in retry_until_success
    result = function()
  File "/code/tests/st/policy/test_felix_gateway.py", line 429, in assert_host_can_not_curl_ext
    self.fail("Internal host can curl external server IP: %s" % self.ext_server_ip)
AssertionError: Internal host can curl external server IP: 172.19.0.2

**Comment by robbrockbank** [comment]
======================================================================
ERROR: test_conflicting_ingress_and_egress_policy_1_deny (tests.st.policy.test_felix_gateway.TestFelixOnGateway)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose_parameterized/parameterized.py", line 365, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/code/tests/st/policy/test_felix_gateway.py", line 330, in test_conflicting_ingress_and_egress_policy
    self.add_host_iface()
  File "/code/tests/st/policy/test_felix_gateway.py", line 413, in add_host_iface
    self._apply_resources(host_endpoint_data, self.gateway)
  File "/code/tests/st/policy/test_felix_gateway.py", line 450, in _apply_resources
    cls._exec_calicoctl("apply", resources, host)
  File "/code/tests/st/policy/test_felix_gateway.py", line 457, in _exec_calicoctl
    host.calicoctl("%s -f new_data" % action)
  File "/code/tests/st/utils/docker_host.py", line 212, in calicoctl
    return self.execute(calicoctl + " " + command)
  File "/code/tests/st/utils/docker_host.py", line 143, in execute
    return log_and_run(command, raise_exception_on_failure=raise_exception_on_failure)
  File "/code/tests/st/utils/utils.py", line 102, in log_and_run
    raise CommandExecError(e)
CommandExecError: Command docker exec -it cali-st-gw sh -c 'export ETCD_AUTHORITY=192.168.122.96:2379; export ETCD_SCHEME=http; export ETCD_CA_CERT

**Comment by fasaxc** [comment]
Looks like a genuine bug; Felix is failing to resolve the endpoint, looks like it's due to the veth being renamed.

**Comment by fasaxc** [comment]
Should be fixed in felix master, we should unskip these once we've got a Felix 2.1.0-rc3 with that fix in it.
