### ISSUE TITLE
calicoctl get BGPConfiguration panics

### ISSUE THREAD

**Issue by bcreane** [projectcalico/calicoctl#1748]
`calicoctl get BGPConfiguration` panics:

```
calicoctl get BGPConfiguration -o wide
panic: template: get:2:161: executing "get" at <.Spec.DefaultNodeASN...>: can't evaluate field DefaultNodeASNumber in type v2.BGPConfigurationSpec

goroutine 1 [running]:
github.com/projectcalico/calicoctl/calicoctl/commands.resourcePrinterTable.print(0x0, 0x0, 0x0, 0xc4203a7b01, 0x1ee3bc0, 0xc4201e8420, 0xc4202ae5c0, 0x1, 0x1, 0x1, ...)
	/home/bcreane/go/src/github.com/projectcalico/calicoctl/calicoctl/commands/printer.go:127 +0x461
github.com/projectcalico/calicoctl/calicoctl/commands.(*resourcePrinterTable).print(0xc42020abc0, 0x1ee3bc0, 0xc4201e8420, 0xc4202ae5c0, 0x1, 0x1, 0x0, 0x156ffbd)
	<autogenerated>:1 +0xa6
github.com/projectcalico/calicoctl/calicoctl/commands.Get(0xc4200d3080, 0x4, 0x4)
	/home/bcreane/go/src/github.com/projectcalico/calicoctl/calicoctl/commands/get.go:183 +0x3b1
main.main()
	/home/bcreane/go/src/github.com/projectcalico/calicoctl/calicoctl/calicoctl.go:83 +0x5f6
```

Interestingly, specifying `yaml` output format for the same resource works fine:

```
./calicoctl get BGPConfiguration -o yaml
apiVersion: projectcalico.org/v2
items:
- apiVersion: projectcalico.org/v2
  kind: BGPConfiguration
  metadata:
    creationTimestamp: null
    name: default
    resourceVersion: "42"
  spec:
    asNumber: 63400
    logSeverityScreen: info
    nodeToNodeMeshEnabled: true
kind: BGPConfigurationList
metadata:
  resourceVersion: "42"
```
## Expected Behavior

Probably should not panic.

## Current Behavior

Panics.

## Steps to Reproduce (for bugs)

1. Setup an etcdv3 datastore with calico v3.0.0-alpha1.
2. Create a bgp resource, e.g.: 
```
apiVersion: projectcalico.org/v2
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: info
  nodeToNodeMeshEnabled: true
  asNumber: 63400
```
3. `calicoctl get BGPConfiguration` # panics
4. `calicoctl get BGPConfiguration -o yaml` # works

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
```
Client Version:    v2.0.0-alpha1
Build date:        2017-10-31T22:48:12+0000
Git commit:        2b700a3a
Cluster Version:   v3.0.0-alpha1-1-gcfce279
Cluster Type:      unknown
```
* calico/node version (e.g. `docker run --rm calico/node versions`)
```
confd v1.0.0-alpha1-rc3
BIRD version 1.6.3
libnetwork-plugin: v1.1.0
calico-bgp-daemon: v0.2.1

Felix:
2017-11-01 00:21:47.662 [INFO][963] logutils.go 83: Early screen log level set to info
Version:            3.0.0-alpha1-rc1
Full git commit ID: 0aba6bc56f0a8990795e2ae491a13bd22b0c4683
Build date:         2017-10-25T01:53:47+0000
```
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by bcreane** [comment]
This was a cluster created vi terraform/kubeadm, specifying "master" tags of calico/node, etc. Weird that confd version is `alpha1-rc3`. Haven't figured out why that's the case yet (calico/_data/versions.yml looks correct for v3.0.0-alpha1).

**Comment by gunjan5** [comment]
i think i know what's wrong. let me attempt a fix in a PR
