### ISSUE TITLE
panic when running `get workloadendpoint`

### ISSUE THREAD

**Issue by shashankv02** [projectcalico/calicoctl#2229]
Following panic occurs when running  `get workloadendpoint` command. The usage might be wrong but didn't expect a panic. 

```
# calicoctl get workloadendpoint docker-registry-docker-registry-proxy-h4n5q -n kube-system
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/projectcalico/libcalico-go/lib/names.ParseWorkloadEndpointName(0x7ffcde1ba748, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/libcalico-go@v1.7.2-0.20201119205058-b367043ede58/lib/names/workloadendpoint.go:264 +0x5b0
github.com/projectcalico/libcalico-go/lib/backend/k8s/conversion.converter.ParseWorkloadEndpointName(...)
	/go/pkg/mod/github.com/projectcalico/libcalico-go@v1.7.2-0.20201119205058-b367043ede58/lib/backend/k8s/conversion/conversion.go:81
github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.(*WorkloadEndpointClient).Get(0xc000448900, 0x1df8da0, 0xc000046040, 0x1e012a0, 0xc000462900, 0x0, 0x0, 0xc0006fedb0, 0x40d948, 0x7fc931c23440)
	/go/pkg/mod/github.com/projectcalico/libcalico-go@v1.7.2-0.20201119205058-b367043ede58/lib/backend/k8s/resources/workloadendpoint.go:178 +0x193
github.com/projectcalico/libcalico-go/lib/backend/k8s.(*KubeClient).Get(0xc0000494c0, 0x1df8da0, 0xc000046040, 0x1e012a0, 0xc000462900, 0x0, 0x0, 0x0, 0x0, 0x203000)
	/go/pkg/mod/github.com/projectcalico/libcalico-go@v1.7.2-0.20201119205058-b367043ede58/lib/backend/k8s/k8s.go:573 +0x313
github.com/projectcalico/libcalico-go/lib/clientv3.(*resources).Get(0xc0003053e0, 0x1df8da0, 0xc000046040, 0x0, 0x0, 0x1b76bdf, 0x10, 0x7ffcde1ba777, 0xb, 0x7ffcde1ba748, ...)
	/go/pkg/mod/github.com/projectcalico/libcalico-go@v1.7.2-0.20201119205058-b367043ede58/lib/clientv3/resources.go:199 +0x1a3
github.com/projectcalico/libcalico-go/lib/clientv3.workloadEndpoints.Get(0x1b74bf7, 0xf, 0x1b7d8af, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/libcalico-go@v1.7.2-0.20201119205058-b367043ede58/lib/clientv3/workloadendpoint.go:100 +0xb8
github.com/projectcalico/calicoctl/calicoctl/resourcemgr.init.13.func4(0x1df8da0, 0xc000046040, 0x1e19680, 0xc0002bcf00, 0x1de5a60, 0xc0003bd680, 0x90, 0x2, 0x98, 0x98)
	/go/src/github.com/projectcalico/calicoctl/calicoctl/resourcemgr/workloadendpoint.go:59 +0xbc
github.com/projectcalico/calicoctl/calicoctl/resourcemgr.resourceHelper.GetOrList(0x1dc26e0, 0xc0003bc240, 0x0, 0x0, 0x1e22760, 0x1a01ae0, 0xc000482680, 0x4, 0x4, 0xc000289260, ...)
	/go/src/github.com/projectcalico/calicoctl/calicoctl/resourcemgr/resourcemgr.go:283 +0xf9
github.com/projectcalico/calicoctl/calicoctl/commands/common.ExecuteResourceAction(0xc000669ce0, 0x1e19680, 0xc0002bcf00, 0x1de5a60, 0xc0003bd680, 0x4, 0x10, 0xc000a7f820, 0x415067, 0xc00088cc68, ...)
	/go/src/github.com/projectcalico/calicoctl/calicoctl/commands/common/resources.go:312 +0x7b7
github.com/projectcalico/calicoctl/calicoctl/commands/common.ExecuteConfigCommand(0xc000669ce0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/projectcalico/calicoctl/calicoctl/commands/common/resources.go:255 +0xa45
github.com/projectcalico/calicoctl/calicoctl/commands.Get(0xc000185310, 0x5, 0x5, 0xc000483400, 0x4)
	/go/src/github.com/projectcalico/calicoctl/calicoctl/commands/get.go:186 +0x2f6
main.main()
	/go/src/github.com/projectcalico/calicoctl/calicoctl/calicoctl.go:107 +0x745
command terminated with exit code 2
```

## Expected Behavior
No panic and proper message

## Steps to Reproduce (for bugs)
1. Installed calicoctl on k8s cluster using `kubectl apply -f https://docs.projectcalico.org/manifests/calicoctl.yaml`
2. Calico version installed on k8s - calico/node:v3.12.3, calico/kube-controllers:v3.12.3

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
```
# calicoctl version
Client Version:    v3.17.0
Git commit:        0e7fc7f7
Cluster Version:   v3.12.3
Cluster Type:      k8s,bgp,kdd
```

* calico/node version (e.g. `docker run --rm calico/node versions`)
v3.12.3

* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
Kubernetes 1.17.2

* Operating System and version:
Ubuntu 16.04

**Comment by bcreane** [comment]
Hi @shashankv02 - suggest you install the same version of `calicoctl` as your backend, ie.:

```
 kubectl apply -f https://docs.projectcalico.org/v3.12/manifests/calicoctl.yaml
```

Let us know if you still see the crash with versions lined up correctly. I'll close for now, but feel free to reopen as necessary.
